stages:
  - deploy

deploy_job:
  stage: deploy
  only:
    - master
  tags:
    - train
  script:
    - rsync -ruog --delete --exclude '.git' --exclude '.gitignore' --exclude 'storage' ./   /volume1/web/tools
    - cd /volume1/web/tools
    - rm -rf ./public/js/app.js
    - rm -rf ./public/css/app.css
#    - git pull https://"$REPO_USER":"$REPO_PASS"@git.ezvh.tw/"$REPO_USER"/"$REPO_NAME".git
    - rm -rf .env
    - cp -f master.env .env
    - php82 composer.phar install
    - php82 artisan migrate
    - php82 artisan optimize:clear
#    - php80 artisan queue:restart
    - npm install
    - npm run prod
